services:
  anal:
    build: .
    image: anal:latest
    volumes:
      - ./output:/app/output
    environment:
      - OUTPUT_DIR=/app/output
    # Edit these parameters before running 'docker compose up'
    command: >
      --page https://example.com
      --duration 60
      --repeatEvery 5
      --serverCount 4
      --header x-server
